### ISSUE TITLE
Compatible with MacOS 10.15?

### ISSUE THREAD

**Issue by balbertalli** [izzyreal/vmpc-binaries#1]
I really like the idea of this project! It brings back fond memories of hunching over that little LCD display for hours.

I've tried to run the Mac binary, but it seems to crash. Here's a bit of the crash report:

Crashed Thread:        0  JUCE Message Thread  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [77013]

Is this binary compatible with 10.15? I tried to compile the Juce version and the plan vmpc repository without much success. If there's a relatively straightforward way to get this running on my Mac, I'd be thrilled!

Oh, and I tried the installer for Windows, which worked without a hitch. However, since I do all my music stuff on the Mac, it would be awesome to get it running in MacOs.

**Comment by izzyreal** [comment]
@balbertalli Thanks for the great feedback!

Did you put `vMPC` in your user home dir? See https://github.com/izzyreal/vmpc-home-dir

I'm working on a Mac installer to smoothen this out.

**Comment by balbertalli** [comment]
I did have vMPC in my home dir, but I cloned it again and now it's working! Thanks for your help!
